USE `SMS_API_V2`;

ALTER TABLE `INVOICE_HISTORY` ADD `INVOICE_TYPE` VARCHAR(10) NOT NULL DEFAULT 'ORIGINAL' AFTER `STATUS`;
ALTER TABLE `INVOICE_HISTORY` ADD `LOCKED_AT` TIMESTAMP NULL DEFAULT NULL AFTER `FILE_NAME`;
ALTER TABLE `INVOICE_PROFILE` ADD `AUTO_GENERATE` TINYINT(1) NOT NULL DEFAULT 0 AFTER `BANK_ID`;
