
ALTER TABLE `USER`
	CHANGE `CREATED_BY` `CREATED_BY` INT NOT NULL ,
	CHANGE `UPDATED_BY` `UPDATED_BY` INT NULL DEFAULT NULL;

ALTER TABLE `USER` ADD INDEX ( `CREATED_BY` );
ALTER TABLE `USER` ADD INDEX ( `UPDATED_BY` );
ALTER TABLE `USER` ADD INDEX ( `ACTIVE` );

ALTER TABLE `USER` ADD FOREIGN KEY ( `CREATED_BY` ) REFERENCES `ADMIN` (
`ADMIN_ID`
) ON DELETE RESTRICT ON UPDATE CASCADE ;

ALTER TABLE `USER` ADD FOREIGN KEY ( `UPDATED_BY` ) REFERENCES `ADMIN` (
`ADMIN_ID`
) ON DELETE RESTRICT ON UPDATE CASCADE ;


--UPDATE SENDER
ALTER TABLE `SENDER` ADD `SENDER_ENABLED` BIT( 1 ) NOT NULL AFTER `SENDER_ID` ,
ADD INDEX ( `SENDER_ENABLED` );

UPDATE SENDER SET SENDER_ENABLED = b'1';