USE `SMS_API_V2`

ALTER TABLE INVOICE_PROFILE 
ADD USE_MIN_COMMITMENT BOOLEAN NOT NULL DEFAULT 0 AFTER APPROVED_POSITION, 
ADD MIN_COMMITMENT_TYPE VARCHAR(15) NOT NULL DEFAULT 'PRICE' AFTER USE_MIN_COMMITMENT,
ADD MIN_COMMITMENT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER MIN_COMMITMENT_TYPE,
ADD MIN_CHARGE DECIMAL(12,2) NULL DEFAULT NULL AFTER MIN_COMMITMENT_AMOUNT,
ADD COMBINED_MIN_COMMITMENT BOOLEAN NOT NULL DEFAULT 1 AFTER MIN_CHARGE ;
