USE `SMS_API_V2`;

ALTER TABLE `INVOICE_HISTORY` ADD `INVOICE_TYPE` VARCHAR(10) NOT NULL DEFAULT 'ORIGINAL' AFTER `STATUS`;
ALTER TABLE `INVOICE_HISTORY` ADD `LOCKED_AT` TIMESTAMP NULL DEFAULT NULL AFTER `FILE_NAME`;
ALTER TABLE `INVOICE_HISTORY` ADD `INVOICE_USAGE` INT UNSIGNED NOT NULL DEFAULT 1 AFTER `INVOICE_TYPE`;
ALTER TABLE `INVOICE_HISTORY` DROP INDEX `INVOICE_NUMBER_UNIQUE`;
