USE `SMS_API_V2`;
--
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE INVOICE_PRODUCT ADD COLUMN USER_API_REPORT VARCHAR(100) DEFAULT NULL AFTER `REPORT_NAME`;
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE INVOICE_SETTING ADD COLUMN LAST_INVOICE_NUMBER INT(10) UNSIGNED NOT NULL AFTER `INVOICE_NUMBER_PREFIX`;
