SET SQL_SAFE_UPDATES = 0 ;

ALTER TABLE BILL_PRICELIST.BILLING_PROFILE_OPERATOR MODIFY COLUMN PER_SMS_PRICE DECIMAL(8,2) UNSIGNED ;
ALTER TABLE BILL_PRICELIST.BILLING_PROFILE_TIERING MODIFY COLUMN PER_SMS_PRICE DECIMAL(8,2) UNSIGNED ;
